---
 - hosts: localhost
   connection: local
   gather_facts: no
   vars_files:
        - key.yml
   tasks:
    - name: Creating EC2 Instance
      ec2:
       # endpoints_path: ec2.ap-south-1.amazonaws.com
        region: ap-south-1
        aws_access_key: "{{ Access_Key_ID }}"
        aws_secret_key: "{{ Secret_Access_Key }}"
        key_name: ebs
        instance_type: t2.micro
        image: ami-5b673c34
        wait: yes
        group: default
        count: 1
        vpc_subnet_id: subnet-4247f80e
        assign_public_ip: yes
      register: x
    - debug: var=x

    - name: Creating EBS Volume   
      ec2_vol:
        region: ap-south-1
        aws_access_key: "{{ Access_Key_ID }}"
        aws_secret_key: "{{ Secret_Access_Key }}"
        volume_size: 3
        volume_type: gp2
        device_name: /dev/xvdf  
        zone: ap-south-1b
        instance: "{{ x.instances[0].id }}"
