---
 - hosts: localhost
   connection: local
   gather_facts: no
   vars_files:
        - key.yml
   tasks:
    - name: Terminating the instance
      ec2:
        region: ap-south-1
        aws_access_key: "{{ Access_Key_ID }}"
        aws_secret_key: "{{ Secret_Access_Key }}"
        instance_ids: [ 'i-0d66e9299316c437c' ]
        state: absent

